use std::fmt;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

use opencodecommit::config::{Config, DiffSource};
use opencodecommit::context;
use opencodecommit::git;
use opencodecommit::sensitive::scan_diff_for_sensitive_content_with_options;
use serde::{Deserialize, Serialize};

use crate::actions::{self, CommitRequest};

const OCC_MANAGED_HOOK_MARKER: &str = "Generated by OpenCodeCommit guard install";
const ALLOW_NEXT_TTL_SECS: u64 = 15 * 60;

const MANAGED_HOOKS: &[&str] = &[
    "applypatch-msg",
    "pre-applypatch",
    "post-applypatch",
    "pre-commit",
    "pre-merge-commit",
    "prepare-commit-msg",
    "commit-msg",
    "post-commit",
    "pre-rebase",
    "post-checkout",
    "post-merge",
    "pre-push",
    "pre-auto-gc",
    "post-rewrite",
    "sendemail-validate",
    "fsmonitor-watchman",
    "p4-changelist",
    "p4-prepare-changelist",
    "p4-post-changelist",
    "p4-pre-submit",
    "post-index-change",
    "reference-transaction",
    "pre-receive",
    "update",
    "proc-receive",
    "post-receive",
    "post-update",
    "push-to-checkout",
];

#[derive(Debug)]
pub enum GuardError {
    Occ(opencodecommit::Error),
    Io(std::io::Error),
    InvalidInstall(String),
}

impl fmt::Display for GuardError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            GuardError::Occ(err) => write!(f, "{err}"),
            GuardError::Io(err) => write!(f, "{err}"),
            GuardError::InvalidInstall(msg) => write!(f, "{msg}"),
        }
    }
}

impl std::error::Error for GuardError {}

impl From<opencodecommit::Error> for GuardError {
    fn from(err: opencodecommit::Error) -> Self {
        Self::Occ(err)
    }
}

impl From<std::io::Error> for GuardError {
    fn from(err: std::io::Error) -> Self {
        Self::Io(err)
    }
}

pub type Result<T> = std::result::Result<T, GuardError>;

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "kebab-case")]
struct GuardInstallMetadata {
    previous_hooks_path: Option<PathBuf>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
struct PreserveMessageToken {
    kind: String,
    index_tree: String,
    expires_at_unix: u64,
}

#[derive(Debug, Clone)]
struct GuardPaths {
    repo_root: PathBuf,
    git_dir: PathBuf,
    root: PathBuf,
    hooks_dir: PathBuf,
    metadata_path: PathBuf,
    allow_next_path: PathBuf,
}

pub fn install() -> Result<String> {
    let paths = resolve_guard_paths()?;
    std::fs::create_dir_all(&paths.hooks_dir)?;

    let existing_metadata = load_metadata_from(&paths.metadata_path).unwrap_or_default();
    let existing_hooks = git::get_local_hooks_path(&paths.repo_root)?;
    let previous_hooks_path = match existing_hooks.as_deref() {
        Some(current) if hooks_path_matches(&paths.repo_root, current, &paths.hooks_dir) => {
            existing_metadata.previous_hooks_path
        }
        Some(current) => Some(current.to_path_buf()),
        None => existing_metadata.previous_hooks_path,
    };

    let metadata = GuardInstallMetadata {
        previous_hooks_path,
    };
    save_metadata_to(&paths.metadata_path, &metadata)?;
    write_managed_hook_wrappers(&paths.hooks_dir, &std::env::current_exe()?)?;
    git::set_local_hooks_path(&paths.repo_root, &managed_hooks_path_value(&paths)?)?;

    Ok(format!(
        "installed repo-local OpenCodeCommit guard at {}",
        paths.hooks_dir.display()
    ))
}

pub fn uninstall() -> Result<String> {
    let paths = resolve_guard_paths()?;
    let metadata = load_metadata_from(&paths.metadata_path).unwrap_or_default();
    let current_hooks = git::get_local_hooks_path(&paths.repo_root)?;

    if current_hooks
        .as_ref()
        .is_some_and(|path| hooks_path_matches(&paths.repo_root, path, &paths.hooks_dir))
    {
        if let Some(previous) = metadata.previous_hooks_path.as_ref() {
            git::set_local_hooks_path(&paths.repo_root, previous)?;
        } else {
            git::unset_local_hooks_path(&paths.repo_root)?;
        }
    }

    if paths.root.exists() {
        std::fs::remove_dir_all(&paths.root)?;
    }

    Ok("uninstalled repo-local OpenCodeCommit guard".to_owned())
}

pub fn status() -> Result<String> {
    let paths = resolve_guard_paths()?;
    let metadata = load_metadata_from(&paths.metadata_path).unwrap_or_default();
    let current_hooks = git::get_local_hooks_path(&paths.repo_root)?;
    let installed = current_hooks
        .as_ref()
        .is_some_and(|path| hooks_path_matches(&paths.repo_root, path, &paths.hooks_dir));

    let mut lines = vec![format!(
        "OpenCodeCommit guard: {}",
        if installed {
            "installed"
        } else {
            "not installed"
        }
    )];
    lines.push(format!("hooks dir: {}", paths.hooks_dir.display()));
    lines.push(format!(
        "core.hooksPath: {}",
        current_hooks
            .as_ref()
            .map(|path| path.display().to_string())
            .unwrap_or_else(|| "(unset)".to_owned())
    ));
    lines.push(format!(
        "previous hooksPath: {}",
        metadata
            .previous_hooks_path
            .as_ref()
            .map(|path| path.display().to_string())
            .unwrap_or_else(|| "(none)".to_owned())
    ));

    Ok(lines.join("\n"))
}

pub fn allow_next_manual() -> Result<String> {
    write_preserve_message_token()?;
    Ok("wrote one-shot manual commit preserve token".to_owned())
}

pub fn allow_next_if_installed() -> Result<bool> {
    if is_installed()? {
        write_preserve_message_token()?;
        Ok(true)
    } else {
        Ok(false)
    }
}

pub fn write_preserve_message_token() -> Result<()> {
    let paths = resolve_guard_paths()?;
    let index_tree = git::write_index_tree(&paths.repo_root)?;
    let token = PreserveMessageToken {
        kind: "preserve-message".to_owned(),
        index_tree,
        expires_at_unix: now_unix_secs() + ALLOW_NEXT_TTL_SECS,
    };
    save_token_to(&paths.allow_next_path, &token)
}

pub fn is_installed() -> Result<bool> {
    let paths = resolve_guard_paths()?;
    is_installed_for_paths(&paths)
}

pub fn is_installed_for_repo(repo_root: &Path) -> Result<bool> {
    let paths = resolve_guard_paths_for_repo(repo_root)?;
    is_installed_for_paths(&paths)
}

pub fn delegate_git_commit(args: &[String]) -> Result<i32> {
    let paths = resolve_guard_paths()?;
    if !is_installed_for_paths(&paths)? {
        return Err(GuardError::InvalidInstall(
            "OpenCodeCommit guard is not installed in this repository. Run 'occ guard install' or use 'occ commit'.".to_owned(),
        ));
    }

    let status = Command::new("git")
        .arg("commit")
        .args(args)
        .current_dir(&paths.repo_root)
        .status()?;
    Ok(status.code().unwrap_or(1))
}

pub fn run_managed_hook(hook_name: &str, args: &[String]) -> Result<i32> {
    let paths = resolve_guard_paths()?;
    let metadata = load_metadata_from(&paths.metadata_path).unwrap_or_default();

    if hook_name == "prepare-commit-msg" {
        run_prepare_commit_msg(&paths, &metadata, args)
    } else {
        chain_hooks(&paths, &metadata, hook_name, args)
    }
}

fn run_prepare_commit_msg(
    paths: &GuardPaths,
    metadata: &GuardInstallMetadata,
    args: &[String],
) -> Result<i32> {
    let config = Config::load_or_default(None)?;
    run_prepare_commit_msg_for_config(paths, metadata, args, &config)
}

fn run_prepare_commit_msg_for_config(
    paths: &GuardPaths,
    metadata: &GuardInstallMetadata,
    args: &[String],
    config: &Config,
) -> Result<i32> {
    let chained = chain_hooks(paths, metadata, "prepare-commit-msg", args)?;
    if chained != 0 {
        return Ok(chained);
    }

    let Some(message_file) = args.first() else {
        return Err(GuardError::InvalidInstall(
            "prepare-commit-msg hook did not receive a commit message file".to_owned(),
        ));
    };

    if consume_matching_allow_next(paths)? {
        return Ok(0);
    }

    let scan_code = scan_staged_diff_with_config(paths, config)?;
    if scan_code != 0 {
        return Ok(scan_code);
    }

    let source = args.get(1).map(String::as_str).unwrap_or("");
    if !should_generate_for_source(source) {
        return Ok(0);
    }

    let message = generate_guard_commit_message(config)?;
    std::fs::write(message_file, format!("{message}\n"))?;
    eprintln!("OpenCodeCommit: raw git commit was handled by occ guard");
    Ok(0)
}

fn scan_staged_diff_with_config(paths: &GuardPaths, config: &Config) -> Result<i32> {
    let diff = match git::get_diff(DiffSource::Staged, &paths.repo_root) {
        Ok(diff) => diff,
        Err(opencodecommit::Error::NoChanges) => return Ok(0),
        Err(err) => return Err(err.into()),
    };

    let changed_files = context::extract_changed_file_paths(&diff);
    let report = scan_diff_for_sensitive_content_with_options(
        &diff,
        &changed_files,
        config.sensitive.enforcement,
        &config.sensitive.allowlist,
    );
    if report.has_blocking_findings() {
        eprintln!("{}", report.format_git_hook_message());
        return Ok(1);
    }
    if report.has_findings() {
        eprintln!("{}", report.format_git_hook_message());
    }
    Ok(0)
}

fn generate_guard_commit_message(config: &Config) -> Result<String> {
    let mut config = config.clone();
    config.diff_source = DiffSource::Staged;
    let request = CommitRequest {
        refine: None,
        feedback: None,
        stdin_diff: None,
        allow_sensitive: true,
    };
    actions::generate_commit_preview_with_fallback(&config, &request, |_| {})
        .map(|preview| preview.message)
        .map_err(|err| {
            GuardError::InvalidInstall(format!(
                "failed to generate commit message in occ guard: {err}"
            ))
        })
}

fn should_generate_for_source(source: &str) -> bool {
    !matches!(source, "merge" | "squash" | "commit")
}

fn consume_matching_allow_next(paths: &GuardPaths) -> Result<bool> {
    let content = match std::fs::read_to_string(&paths.allow_next_path) {
        Ok(content) => content,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(false),
        Err(err) => return Err(err.into()),
    };

    let token = match toml::from_str::<PreserveMessageToken>(&content) {
        Ok(token) => token,
        Err(_) => {
            let _ = std::fs::remove_file(&paths.allow_next_path);
            return Ok(false);
        }
    };

    if token.kind != "preserve-message" || now_unix_secs() > token.expires_at_unix {
        let _ = std::fs::remove_file(&paths.allow_next_path);
        return Ok(false);
    }

    let index_tree = git::write_index_tree(&paths.repo_root)?;
    if token.index_tree == index_tree {
        let _ = std::fs::remove_file(&paths.allow_next_path);
        return Ok(true);
    }

    Ok(false)
}

fn resolve_guard_paths() -> Result<GuardPaths> {
    let repo_root = git::get_repo_root()?;
    resolve_guard_paths_for_repo(&repo_root)
}

fn resolve_guard_paths_for_repo(repo_root: &Path) -> Result<GuardPaths> {
    let git_dir = git::get_git_dir(repo_root)?;
    let root = git_dir.join("occ");
    Ok(GuardPaths {
        repo_root: repo_root.to_path_buf(),
        git_dir,
        hooks_dir: root.join("hooks"),
        metadata_path: root.join("guard.toml"),
        allow_next_path: root.join("allow-next.toml"),
        root,
    })
}

fn managed_hooks_path_value(paths: &GuardPaths) -> Result<PathBuf> {
    let default_git_dir = paths.repo_root.join(".git");
    if same_path(&paths.git_dir, &default_git_dir) {
        Ok(PathBuf::from(".git").join("occ").join("hooks"))
    } else {
        Ok(paths.hooks_dir.clone())
    }
}

fn is_installed_for_paths(paths: &GuardPaths) -> Result<bool> {
    Ok(git::get_local_hooks_path(&paths.repo_root)?
        .as_ref()
        .is_some_and(|path| hooks_path_matches(&paths.repo_root, path, &paths.hooks_dir)))
}

fn load_metadata_from(path: &Path) -> Result<GuardInstallMetadata> {
    let content = std::fs::read_to_string(path)?;
    toml::from_str(&content).map_err(|err| {
        GuardError::InvalidInstall(format!(
            "failed to parse guard metadata {}: {err}",
            path.display()
        ))
    })
}

fn save_metadata_to(path: &Path, metadata: &GuardInstallMetadata) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let content = toml::to_string(metadata).map_err(|err| {
        GuardError::InvalidInstall(format!("failed to serialize guard metadata: {err}"))
    })?;
    std::fs::write(path, content)?;
    Ok(())
}

fn save_token_to(path: &Path, token: &PreserveMessageToken) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let content = toml::to_string(token).map_err(|err| {
        GuardError::InvalidInstall(format!("failed to serialize guard token: {err}"))
    })?;
    std::fs::write(path, content)?;
    Ok(())
}

fn write_managed_hook_wrappers(hooks_dir: &Path, occ_path: &Path) -> Result<()> {
    let escaped_occ_path = shell_single_quote(occ_path);
    let script = format!(
        r#"#!/bin/sh
# {marker}
HOOK_NAME=$(basename "$0")
if [ "${{OCC_CHAINED_HOOK_NAME:-}}" = "$HOOK_NAME" ]; then
    exit 0
fi
OCC_BIN='{occ_path}'
if [ -x "$OCC_BIN" ]; then
    exec "$OCC_BIN" internal run-managed-hook "$HOOK_NAME" "$@"
fi
if command -v occ >/dev/null 2>&1; then
    exec occ internal run-managed-hook "$HOOK_NAME" "$@"
fi
if command -v opencodecommit >/dev/null 2>&1; then
    exec opencodecommit internal run-managed-hook "$HOOK_NAME" "$@"
fi
echo "OpenCodeCommit guard error: occ executable not found. Reinstall with 'occ guard install'." >&2
exit 1
"#,
        marker = OCC_MANAGED_HOOK_MARKER,
        occ_path = escaped_occ_path,
    );

    for hook_name in MANAGED_HOOKS {
        let hook_path = hooks_dir.join(hook_name);
        std::fs::write(&hook_path, &script)?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&hook_path, std::fs::Permissions::from_mode(0o755))?;
        }
    }

    Ok(())
}

fn chain_hooks(
    paths: &GuardPaths,
    metadata: &GuardInstallMetadata,
    hook_name: &str,
    args: &[String],
) -> Result<i32> {
    let mut candidates = Vec::new();

    if let Some(previous) = metadata.previous_hooks_path.as_ref()
        && previous != Path::new("/dev/null")
    {
        candidates.push(resolve_hooks_path(&paths.repo_root, previous).join(hook_name));
    }

    candidates.push(paths.git_dir.join("hooks").join(hook_name));

    let mut seen = vec![paths.hooks_dir.join(hook_name)];
    for candidate in candidates {
        if should_run_hook(&candidate, &seen)? {
            let code = run_hook_script(&candidate, hook_name, args)?;
            if code != 0 {
                return Ok(code);
            }
            seen.push(candidate);
        }
    }

    Ok(0)
}

fn should_run_hook(candidate: &Path, seen: &[PathBuf]) -> Result<bool> {
    if !candidate.exists() || !is_executable(candidate)? {
        return Ok(false);
    }
    if seen.iter().any(|seen| same_path(candidate, seen)) {
        return Ok(false);
    }
    if is_occ_managed_hook(candidate)? {
        return Ok(false);
    }
    Ok(true)
}

fn is_executable(path: &Path) -> Result<bool> {
    let metadata = std::fs::metadata(path)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        Ok(metadata.permissions().mode() & 0o111 != 0)
    }
    #[cfg(not(unix))]
    {
        Ok(metadata.is_file())
    }
}

fn is_occ_managed_hook(path: &Path) -> Result<bool> {
    match std::fs::read_to_string(path) {
        Ok(content) => Ok(content.contains(OCC_MANAGED_HOOK_MARKER)),
        Err(err) if err.kind() == std::io::ErrorKind::InvalidData => Ok(false),
        Err(err) => Err(err.into()),
    }
}

fn run_hook_script(path: &Path, hook_name: &str, args: &[String]) -> Result<i32> {
    let status = Command::new(path)
        .args(args)
        .env("OCC_CHAINED_HOOK_NAME", hook_name)
        .status()?;
    Ok(status.code().unwrap_or(1))
}

fn hooks_path_matches(repo_root: &Path, hooks_path: &Path, managed_hooks_dir: &Path) -> bool {
    same_path(
        &resolve_hooks_path(repo_root, hooks_path),
        managed_hooks_dir,
    )
}

fn resolve_hooks_path(repo_root: &Path, path: &Path) -> PathBuf {
    if path.is_absolute() {
        path.to_path_buf()
    } else {
        repo_root.join(path)
    }
}

fn same_path(a: &Path, b: &Path) -> bool {
    match (a.canonicalize(), b.canonicalize()) {
        (Ok(a), Ok(b)) => a == b,
        _ => a == b,
    }
}

fn shell_single_quote(path: &Path) -> String {
    path.to_string_lossy().replace('\'', "'\"'\"'")
}

fn now_unix_secs() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|duration| duration.as_secs())
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::process::Command;

    fn setup_repo(name: &str) -> PathBuf {
        let dir =
            std::env::temp_dir().join(format!("occ-guard-repo-{}-{}", std::process::id(), name));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        let run = |args: &[&str]| {
            Command::new("git")
                .args(args)
                .current_dir(&dir)
                .env("GIT_AUTHOR_NAME", "Test")
                .env("GIT_AUTHOR_EMAIL", "test@test.com")
                .env("GIT_COMMITTER_NAME", "Test")
                .env("GIT_COMMITTER_EMAIL", "test@test.com")
                .output()
                .unwrap()
        };

        run(&["init"]);
        run(&["config", "user.email", "test@test.com"]);
        run(&["config", "user.name", "Test"]);
        fs::write(dir.join("README.md"), "# Hello").unwrap();
        run(&["add", "README.md"]);
        run(&["commit", "-m", "initial commit"]);

        dir
    }

    fn write_hook_script(path: &Path, line: &str) {
        fs::write(
            path,
            format!("#!/bin/sh\necho {line} >> \"$OCC_TEST_HOOK_LOG\"\n"),
        )
        .unwrap();
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(path, fs::Permissions::from_mode(0o755)).unwrap();
        }
    }

    fn with_repo<T>(repo: &Path, f: impl FnOnce() -> T) -> T {
        let _lock = opencodecommit::TEST_CWD_LOCK.lock().unwrap();
        let original = std::env::current_dir().unwrap();
        std::env::set_current_dir(repo).unwrap();
        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(f));
        std::env::set_current_dir(original).unwrap();
        match result {
            Ok(value) => value,
            Err(payload) => std::panic::resume_unwind(payload),
        }
    }

    #[test]
    fn install_status_uninstall_sets_and_restores_local_hooks_path() {
        let repo = setup_repo("install-status");
        let previous = repo.join("custom-hooks");
        fs::create_dir_all(&previous).unwrap();
        Command::new("git")
            .args([
                "config",
                "--local",
                "core.hooksPath",
                previous.to_str().unwrap(),
            ])
            .current_dir(&repo)
            .output()
            .unwrap();

        with_repo(&repo, || {
            let installed = install().unwrap();
            assert!(installed.contains("repo-local OpenCodeCommit guard"));
            assert!(is_installed().unwrap());
            let status = status().unwrap();
            assert!(status.contains("OpenCodeCommit guard: installed"));
            assert!(status.contains("previous hooksPath"));

            let uninstalled = uninstall().unwrap();
            assert!(uninstalled.contains("uninstalled repo-local"));
            assert!(!is_installed().unwrap());
            let restored = git::get_local_hooks_path(&repo).unwrap().unwrap();
            assert!(same_path(&restored, &previous));
        });

        let _ = fs::remove_dir_all(repo);
    }

    #[test]
    fn writes_managed_hook_wrappers() {
        let repo = setup_repo("wrappers");
        with_repo(&repo, || {
            let paths = resolve_guard_paths().unwrap();
            fs::create_dir_all(&paths.hooks_dir).unwrap();
            write_managed_hook_wrappers(&paths.hooks_dir, Path::new("/tmp/occ")).unwrap();

            let prepare = fs::read_to_string(paths.hooks_dir.join("prepare-commit-msg")).unwrap();
            let commit_msg = fs::read_to_string(paths.hooks_dir.join("commit-msg")).unwrap();
            assert!(prepare.contains(OCC_MANAGED_HOOK_MARKER));
            assert!(prepare.contains("internal run-managed-hook"));
            assert!(commit_msg.contains(OCC_MANAGED_HOOK_MARKER));
        });

        let _ = fs::remove_dir_all(repo);
    }

    #[test]
    fn prepare_commit_msg_blocks_sensitive_diff_before_generation() {
        let repo = setup_repo("prepare-sensitive");
        with_repo(&repo, || {
            fs::write(".env", "API_KEY=secret\n").unwrap();
            Command::new("git").args(["add", ".env"]).output().unwrap();

            let paths = resolve_guard_paths().unwrap();
            fs::create_dir_all(&paths.hooks_dir).unwrap();
            let metadata = GuardInstallMetadata::default();
            let message_file = repo.join(".git/COMMIT_EDITMSG");
            fs::write(&message_file, "agent message").unwrap();
            let config = Config {
                sensitive: opencodecommit::config::SensitiveConfig {
                    enforcement: opencodecommit::sensitive::SensitiveEnforcement::BlockAll,
                    allowlist: vec![],
                },
                ..Config::default()
            };

            let code = run_prepare_commit_msg_for_config(
                &paths,
                &metadata,
                &[
                    message_file.to_string_lossy().to_string(),
                    "message".to_owned(),
                ],
                &config,
            )
            .unwrap();
            assert_eq!(code, 1);
            assert_eq!(fs::read_to_string(&message_file).unwrap(), "agent message");
        });

        let _ = fs::remove_dir_all(repo);
    }

    #[test]
    fn allow_next_preserves_message_once_for_matching_index_tree() {
        let repo = setup_repo("allow-next");
        with_repo(&repo, || {
            fs::write("file.txt", "content").unwrap();
            Command::new("git")
                .args(["add", "file.txt"])
                .output()
                .unwrap();
            write_preserve_message_token().unwrap();

            let paths = resolve_guard_paths().unwrap();
            assert!(consume_matching_allow_next(&paths).unwrap());
            assert!(!paths.allow_next_path.exists());
            assert!(!consume_matching_allow_next(&paths).unwrap());
        });

        let _ = fs::remove_dir_all(repo);
    }

    #[test]
    fn allow_next_does_not_match_changed_index_tree() {
        let repo = setup_repo("allow-next-mismatch");
        with_repo(&repo, || {
            fs::write("file.txt", "content").unwrap();
            Command::new("git")
                .args(["add", "file.txt"])
                .output()
                .unwrap();
            write_preserve_message_token().unwrap();

            fs::write("other.txt", "other").unwrap();
            Command::new("git")
                .args(["add", "other.txt"])
                .output()
                .unwrap();

            let paths = resolve_guard_paths().unwrap();
            assert!(!consume_matching_allow_next(&paths).unwrap());
            assert!(paths.allow_next_path.exists());
        });

        let _ = fs::remove_dir_all(repo);
    }

    #[test]
    fn existing_hooks_are_chained_before_prepare_guard_logic() {
        let repo = setup_repo("chain-prepare");
        let log_path = repo.join("hooks.log");
        with_repo(&repo, || {
            let paths = resolve_guard_paths().unwrap();
            let previous = repo.join("previous-hooks");
            fs::create_dir_all(&previous).unwrap();
            write_hook_script(&previous.join("prepare-commit-msg"), "previous");
            write_hook_script(&repo.join(".git/hooks/prepare-commit-msg"), "default");
            let metadata = GuardInstallMetadata {
                previous_hooks_path: Some(previous),
            };

            fs::write("file.txt", "content").unwrap();
            Command::new("git")
                .args(["add", "file.txt"])
                .output()
                .unwrap();
            write_preserve_message_token().unwrap();
            let message_file = repo.join(".git/COMMIT_EDITMSG");
            fs::write(&message_file, "manual").unwrap();

            unsafe {
                std::env::set_var("OCC_TEST_HOOK_LOG", &log_path);
            }
            let code = run_prepare_commit_msg(
                &paths,
                &metadata,
                &[message_file.to_string_lossy().to_string()],
            )
            .unwrap();
            assert_eq!(code, 0);
            let log = fs::read_to_string(&log_path).unwrap();
            assert!(log.contains("previous"));
            assert!(log.contains("default"));
        });
        unsafe {
            std::env::remove_var("OCC_TEST_HOOK_LOG");
        }

        let _ = fs::remove_dir_all(repo);
    }
}
